;DEPENDENCY DECLARATIONS
declare i32 @printf(i8*, ...)
declare i32 @sprintf(i8*,i8*, ...)
declare i8* @strcat(i8*,i8*)
declare i8* @strcpy(i8*,i8*)
@.str.newline = constant [2 x i8] c"\0A\00"
@.str.int = constant [3 x i8] c"%d\00"
@.str.double = constant [4 x i8] c"%lf\00"
@.str.space = constant [2 x i8] c" \00"
;GLOBAL DECLARATIONS

@.str.0 = constant [13 x i8] c"wow it works\00"
@.str.1 = constant [54 x i8] c"Here is the string generated by the function strtest:\00"
;GLOBAL INITIALIZATIONS OF GLOBAL VARIABLES THAT ARE STRINGS OR ARRAYS OF STRINGS
define void @globalinit(){
ret void
}

define i8* @strtest (i32 %a){
%1 = alloca i32
store i32 %a, i32* %1
%2= load i32,i32* %1
%3= icmp eq i32 %2,0
br i1 %3, label %if.body.0, label %if.elif.0.0
if.body.0:
%4 = getelementptr inbounds [13 x i8], [13 x i8]* @.str.0 , i32 0, i32 0
ret i8* %4
br label %if.exit.0.0
if.elif.0.0:
br label %if.exit.0.0
if.exit.0.0:
ret i8* getelementptr inbounds([2 x i8],[2 x i8]* @.str.space,i32 0,i32 0)
}
define void @main (){
call void () @globalinit()
%1 = getelementptr inbounds [54 x i8], [54 x i8]* @.str.1 , i32 0, i32 0
%2 = call i32 (i8*, ...) @printf(i8* %1)
%3= call i32 (i8*, ...) @printf(i8* getelementptr inbounds([2 x i8],[2 x i8]* @.str.space,i32 0,i32 0))
%4 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds([2 x i8], [2 x i8]* @.str.newline, i32 0, i32 0))
%5=call i8* (i32) @strtest(i32 1)
%6 = call i32 (i8*, ...) @printf(i8* %5)
%7= call i32 (i8*, ...) @printf(i8* getelementptr inbounds([2 x i8],[2 x i8]* @.str.space,i32 0,i32 0))
%8 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds([2 x i8], [2 x i8]* @.str.newline, i32 0, i32 0))
ret void
}

