let stgl="wow"
let globArrStr=[[["wow","you are"],["so","kind"]],[["how is","this possible"],["thank you","very much"]]]
func strtest(_ a: Int) -> String {
    if a==0{
        let st=stgl+" it works"
        return st
    }
}
func printStr() {
    for i in 0..<2{
        for j in 0..<2{
            for z in 0..<2{
                print(globArrStr[i][j][z])
            }
            println()
        }
        println()
    }
}
func printStrLocal(_ arrStr:[[[String]]]) {
    for i in 0..<2{
        for j in 0..<2{
            for z in 0..<2{
                print(arrStr[i][j][z])
            }
            println()
        }
        println()
    }
}
func main(){
    println("Here is the string generated by the function strtest:")
    println(strtest(0))
    println("\nHere is the global array of strings printed:")
    printStr()
    let locArrStr=[[["first","second"],["third","fourth"]],[["fifth","sixt"],["seventh","eight"]]]
    println("Here is instead the local one:")
    printStrLocal(locArrStr)
}